version: '3'
services:
  top.api:
    image: ghcr.io/denisjet/mytodo-server/mytodo-server:latest
    container_name: mytodo-server
    restart: always
    ports:
      - 3001:3001
    volumes:
      - ./.env:/mytodo-server/.env